[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs download --probe 0d28:0204 --chip STM32F469NIHx"

[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf"