[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "pyocd load --format elf"
runner = "pyocd flash -t stm32f446rex --format elf"

[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf"